{
 "title": "CloudStack Management",
 "description": "Metrics from the native plugin Prometheus Exporter of CloudStack ",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "management",
    "label": "Management Server",
    "query": {
     "query": "label_values({job=\"management\"},instance)"
    }
   },
   { "name": "Filters" },
   {
    "name": "hostname",
    "query": {
     "query": "label_values(cloudstack_host_cpu_usage_mhz_total, hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Host status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(ip) (cloudstack_hosts_total{filter=\"online\"}))",
     "legendFormat": "Online"
    },
    {
     "expr": "(sum by(ip) (cloudstack_hosts_total{ filter=\"offline\"})) ",
     "legendFormat": "Offline"
    }
   ]
  },
  {
   "title": "Cloudstack port",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox-port\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cloudstack_api_success", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Overview Used / Allocated",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (name)(cloudstack_storage_pool_gibs_total{ filter=\"used\", type=\"secondary\"})",
     "legendFormat": "{{name}}"
    },
    { "expression": "($A / $B) * 100", "reducer": "mean", "type": "math" },
    { "expression": "($D / $C) * 100", "type": "math" },
    { "expression": "( $E / $F ) * 100", "type": "math" }
   ]
  },
  {
   "title": "cloudstack management service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "label_replace(\r\n  node_systemd_unit_state{name=\"cloudstack-management.service\", state=~\"active|failed|inactive|deactivating|activating\"} == 1,\r\n  \"status\", \"$1\", \"state\", \"(.*)\"\r\n)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "cloudstack usage service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 3 },
   "targets": [
    {
     "expr": "label_replace(\r\n  node_systemd_unit_state{name=\"cloudstack-usage.service\", state=~\"active|failed|inactive|deactivating|activating\"} == 1,\r\n  \"status\", \"$1\", \"state\", \"(.*)\"\r\n)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "CPU Used / Allocated",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($A / $B) * 100", "type": "math" }
   ]
  },
  {
   "title": "RAM Used / Allocated",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($A / $B) * 100  ", "type": "math" }
   ]
  },
  {
   "title": "Instances Running",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cloudstack_host_vms_total", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "Instances  state",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cloudstack_vms_total", "legendFormat": "{{filter}}" }
   ]
  },
  {
   "title": "Network",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(cloudstack_vlans_total{ filter=\"allocated\"}) * 100) / sum(cloudstack_vlans_total{filter=\"total\"})",
     "legendFormat": "VLANs Allocated"
    },
    {
     "expr": "(sum(cloudstack_private_ips_total{ filter=\"allocated\"}) * 100) / sum(cloudstack_private_ips_total{ filter=\"total\"})",
     "legendFormat": "Private IPs Allocated"
    },
    {
     "expr": "(sum(cloudstack_public_ips_total{ filter=\"allocated\"}) * 100) / sum(cloudstack_public_ips_total{ filter=\"total\"})",
     "legendFormat": "Public IPs Allocated"
    },
    {
     "expr": "(sum(cloudstack_shared_network_ips_total{ filter=\"allocated\"}) * 100) / sum(cloudstack_shared_network_ips_total{ filter=\"total\"})",
     "legendFormat": "Shared Net IPs Allocated"
    }
   ]
  },
  {
   "title": "Domains",
   "type": "table",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 12 },
   "targets": [
    {
     "expr": "sum by(domain) (cloudstack_domain_resource_count{type=\"cpu\"})",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum by(domain) (cloudstack_domain_resource_count{type=\"memory\"})",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}