{
 "title": "JMX prometheus exporter",
 "description": "Complete dashboard using metrics from prometheus JMX exporter, with drill down per release > pod",
 "tags": [ "JVM" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "release", "label": "release", "query": "label_values(release)" },
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Heap used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "( sum by(job)  (jvm_memory_bytes_used{area=\"heap\",job=\"$job\"})*100) / sum by(job) (jvm_memory_bytes_max{area=\"heap\",job=\"$job\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsUS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg by (job)(process_start_time_seconds{job=\"$job\"})*1000)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - max by(job) (process_start_time_seconds{job=\"$job\"}))\r\n",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_info{job=\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Heap",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\", job=\"$job\"}",
     "legendFormat": "Used {{job}}"
    },
    {
     "expr": " jvm_memory_bytes_max{area=\"heap\",job=\"$job\"}",
     "legendFormat": "Max {{job}}"
    }
   ]
  },
  {
   "title": "Non Heap",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"nonheap\",job=\"$job\"}",
     "legendFormat": "Used  {{job}}"
    }
   ]
  },
  {
   "title": "PS Eden Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{ pool=\"PS Eden Space\",job=\"$job\"}",
     "legendFormat": "Max  {{job}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"PS Eden Space\",job=\"$job\"}",
     "legendFormat": "Used  {{job}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"PS Eden Space\",job=\"$job\"}",
     "legendFormat": "Committed  {{job}}"
    }
   ]
  },
  {
   "title": "PS Old Gen",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{ pool=\"PS Old Gen\",job=\"$job\"}",
     "legendFormat": "Max  {{job}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"PS Old Gen\",job=\"$job\"}",
     "legendFormat": "Used  {{job}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{ pool=\"PS Old Gen\",job=\"$job\"}",
     "legendFormat": "Committed  {{job}}"
    }
   ]
  },
  {
   "title": "PS Survivor Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"PS Survivor Space\",job=\"$job\"}",
     "legendFormat": "Max  {{job}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"PS Survivor Space\",job=\"$job\"}",
     "legendFormat": "Used  {{job}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"PS Survivor Space\",job=\"$job\"}",
     "legendFormat": "Committed  {{job}}"
    }
   ]
  },
  {
   "title": "Metaspace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"Metaspace\",job=\"$job\"}",
     "legendFormat": "Max {{job}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"Metaspace\",job=\"$job\"}",
     "legendFormat": "Used {{job}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"Metaspace\",job=\"$job\"}",
     "legendFormat": "Committed {{job}}"
    }
   ]
  },
  {
   "title": "Compressed Class Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"Compressed Class Space\",job=\"$job\"}",
     "legendFormat": "Max {{job}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"Compressed Class Space\",job=\"$job\"}",
     "legendFormat": "Used {{job}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"Compressed Class Space\",job=\"$job\"}",
     "legendFormat": "Committed {{job}}"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_current{job=\"$job\"}",
     "legendFormat": "JVM current threads  {{job}}"
    },
    {
     "expr": "jvm_threads_daemon{job=\"$job\"}",
     "legendFormat": "JVM daemon threads {{job}}"
    },
    {
     "expr": "jvm_threads_deadlocked{job=\"$job\"}",
     "legendFormat": "JVM deadlocked threads  {{job}}"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{job=\"$job\"}",
     "legendFormat": "{{gc}}  {{job}}"
    }
   ]
  },
  {
   "title": "GC time / 1 min. rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{job=\"$job\"}[5m])",
     "legendFormat": "{{gc}} {{job}}"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_classes_loaded_total{job=\"$job\"}",
     "legendFormat": "loaded  {{job}}"
    }
   ]
  }
 ]
}