{
 "title": "Server Health monitoring",
 "description": "Server Health monitoring",
 "tags": [
  "staging",
  "commin-infra"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{job=\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU Load 5m",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load5{job=\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance, job) (\r\n  irate(node_cpu_seconds_total{mode=~\"user|system\",job=\"$job\"}[1m])\r\n)\r\n/\r\ncount by(instance, job) (node_cpu_seconds_total{mode=\"user\",job=\"$job\"})\r\n* 100",
     "legendFormat": "Utilization {{job}}"
    }
   ]
  },
  {
   "title": "RAM used ",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (node_memory_MemTotal_bytes{job=\"$job\"} - node_memory_MemAvailable_bytes{job=\"$job\"}) / node_memory_MemTotal_bytes{job=\"$job\"}\r\n",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (job, mountpoint)(\r\n  (\r\n    node_filesystem_size_bytes{fstype=~\"xfs|ext4\",job=\"$job\"}\r\n    - node_filesystem_avail_bytes{fstype=~\"xfs|ext4\",job=\"$job\"}\r\n  ) / node_filesystem_size_bytes{fstype=~\"xfs|ext4\",job=\"$job\"} * 100\r\n)\r\n",
     "legendFormat": "{{job}} ({{mountpoint}})"
    }
   ]
  },
  {
   "title": "cloudstack agent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(   node_systemd_unit_state{name=\"cloudstack-agent.service\", state=~\"active|failed|inactive|deactivating|activating\",job=\"$job\"} == 1 ,   \"status\", \"$1\", \"state\", \"(.*)\" )",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "libvirtd service",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(   node_systemd_unit_state{name=\"libvirtd.service\", state=~\"active|failed|inactive|deactivating|activating\",job=\"$job\"} == 1,   \"status\", \"$1\", \"state\", \"(.*)\" )",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "node_systemd_unit_state{name=\"libvirtd.service\", state=\"active\"} == 0",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}