{
 "title": "Server Health monitoring - historical",
 "description": "Server Health monitoring",
 "tags": [
  "staging",
  "commin-infra"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{job=\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU Load 5m",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 9, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "node_load5{job=\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 *\r\navg by (job, mountpoint) (\r\n  (\r\n    node_filesystem_size_bytes{fstype=~\"xfs|ext4\",job=\"$job\"}\r\n    -\r\n    node_filesystem_free_bytes{fstype=~\"xfs|ext4\",job=\"$job\"}\r\n  )\r\n  /\r\n  node_filesystem_size_bytes{fstype=~\"xfs|ext4\",job=\"$job\"}\r\n)\r\n",
     "legendFormat": "{{job}} ({{mountpoint}})"
    }
   ]
  },
  {
   "title": "cloudstack agent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(   node_systemd_unit_state{name=\"cloudstack-agent.service\", state=~\"active|failed|inactive|deactivating|activating\",job=\"$job\"} == 1 ,   \"status\", \"$1\", \"state\", \"(.*)\" )",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "libvirtd service",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 7, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(   node_systemd_unit_state{name=\"libvirtd.service\", state=~\"active|failed|inactive|deactivating|activating\",job=\"$job\"} == 1,   \"status\", \"$1\", \"state\", \"(.*)\" )",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "node_systemd_unit_state{name=\"libvirtd.service\", state=\"active\"} == 0",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 *\r\nsum by(instance, job) (\r\n  irate(node_cpu_seconds_total{mode=\"system\", job=\"$job\"}[5m])\r\n)\r\n/\r\ncount by(instance, job) (\r\n  node_cpu_seconds_total{mode=\"idle\", job=\"$job\"}\r\n)\r\n\r\n",
     "legendFormat": "Busy System {{job}}"
    },
    {
     "expr": "100 *\r\nsum by(instance, job) (\r\n  irate(node_cpu_seconds_total{mode=\"user\", job=\"$job\"}[5m])\r\n)\r\n/\r\ncount by(instance, job) (\r\n  node_cpu_seconds_total{mode=\"idle\", job=\"$job\"}\r\n)\r\n\r\n",
     "legendFormat": "Busy User {{job}}"
    },
    {
     "expr": "100 *\r\nsum by(instance, job) (\r\n  irate(node_cpu_seconds_total{mode=\"iowait\", job=\"$job\"}[5m])\r\n)\r\n/\r\ncount by(instance, job) (\r\n  node_cpu_seconds_total{mode=\"idle\", job=\"$job\"}\r\n)\r\n\r\n",
     "legendFormat": "Busy Iowait {{job}}"
    },
    {
     "expr": "100 *\r\nsum by (instance, job) (\r\n  irate(node_cpu_seconds_total{mode=~\"irq|softirq\", job=\"$job\"}[5m])\r\n)\r\n/\r\ncount by (instance, job) (\r\n  node_cpu_seconds_total{mode=\"idle\", job=\"$job\"}\r\n)\r\n\r\n",
     "legendFormat": "Busy IRQs {{job}}"
    },
    {
     "expr": "100 - (\r\n  sum by(instance, job) (\r\n    irate(node_cpu_seconds_total{mode=\"idle\",job=\"$job\"}[5m])\r\n  )\r\n  /\r\n  count by(instance, job) (\r\n    node_cpu_seconds_total{mode=\"idle\",job=\"$job\"}\r\n  )\r\n  * 100\r\n)\r\n",
     "legendFormat": "Busy Other {{job}}"
    },
    {
     "expr": "100 - (\r\n  sum by(instance, job) (\r\n    irate(node_cpu_seconds_total{mode=\"idle\",job=\"$job\"}[5m])\r\n  )\r\n  /\r\n  count by(instance, job) (\r\n    node_cpu_seconds_total{mode=\"idle\",job=\"$job\"}\r\n  )\r\n  * 100\r\n)\r\n",
     "legendFormat": "Idle {{job}}"
    },
    {
     "expr": "100 *\r\nsum by (instance, job) (\r\n  rate(node_cpu_seconds_total{mode=~\"user|system\", job=\"$job\"}[1m])\r\n)\r\n/\r\ncount by (instance, job) (\r\n  node_cpu_seconds_total{mode=\"user\", job=\"$job\"}\r\n)\r\n",
     "legendFormat": "Utilization {{job}}"
    }
   ]
  },
  {
   "title": "RAM used ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (\r\n  1 - (\r\n    node_memory_MemAvailable_bytes{job=\"$job\"} \r\n    / \r\n    node_memory_MemTotal_bytes{job=\"$job\"}\r\n  )\r\n)\r\n",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}