{
 "title": "Stackbill JVM Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "Service", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Up Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Days" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{instance=\"$instance\"}/ 86400",
     "legendFormat": "{{days}}"
    }
   ]
  },
  {
   "title": "Start Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{instance=\"$instance\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(jvm_memory_used_bytes{area=\"heap\",instance=\"$instance\"}) / sum(jvm_memory_max_bytes{area=\"heap\",instance=\"$instance\"} unless jvm_memory_max_bytes{area=\"heap\",instance=\"$instance\"} == -1)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Non Heap Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(jvm_memory_used_bytes{area=\"nonheap\",instance=\"$instance\"}) / sum(jvm_memory_max_bytes{area=\"nonheap\",instance=\"$instance\"} unless jvm_memory_max_bytes{area=\"nonheap\",instance=\"$instance\"} == -1)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "I/O Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "sum by (status, uri) (rate(http_server_requests_seconds_count{instance=\"$instance\", uri!=\"\"}[1m]) * 60)",
       "legendFormat": "{{ uri }} {{  status }}"
      }
     ]
    },
    {
     "title": "Rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{ instance=\"$instance\"}[1m]))",
       "legendFormat": "HTTP"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 55 },
     "targets": [
      {
       "expr": "sum(avg_over_time(http_server_requests_seconds_sum[1m])) / sum(avg_over_time(http_server_requests_seconds_count[1m])) * 1000",
       "legendFormat": "HTTP - Avg (1m)"
      },
      {
       "expr": "max(http_server_requests_seconds_max) * 1000",
       "legendFormat": "HTTP - Max"
      }
     ]
    },
    {
     "title": "Utilization",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 61 },
     "targets": [
      {
       "expr": "tomcat_threads_busy{ instance=\"$instance\"}",
       "legendFormat": "tomcat bsy"
      },
      {
       "expr": "tomcat_threads_current{ instance=\"$instance\"}",
       "legendFormat": "tomcat cur"
      },
      {
       "expr": "tomcat_threads_config_max{instance=\"$instance\"}",
       "legendFormat": "tomcat max"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 61 },
     "targets": [
      { "expr": "app_io_errors_total", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Heap",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{area=\"heap\",instance=\"$instance\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{area=\"heap\",instance=\"$instance\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{area=\"heap\",instance=\"$instance\"} > 0)",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Non-Heap",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{area=\"nonheap\",instance=\"$instance\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{area=\"nonheap\",instance=\"$instance\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{area=\"nonheap\",instance=\"$instance\"} > 0)",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Total",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{ instance=\"$instance\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{ instance=\"$instance\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{ instance=\"$instance\"} > 0)",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  { "title": "JVM Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "system_cpu_usage{instance=\"$instance\"} * 100",
     "legendFormat": "system"
    },
    {
     "expr": "process_cpu_usage{instance=\"$instance\"} * 100",
     "legendFormat": "process"
    },
    {
     "expr": "(rate(process_cpu_time_ns_total{instance=\"$instance\"}[$__rate_interval]) / 1e9 / system_cpu_count{instance=\"$instance\"}) * 100",
     "legendFormat": "process-15m"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "system_load_average_1m{instance=\"$instance\"}",
     "legendFormat": "system-1m"
    },
    {
     "expr": "system_cpu_count{instance=\"$instance\"}",
     "legendFormat": "cpu's"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{ instance=\"$instance\"}",
     "legendFormat": "live"
    },
    {
     "expr": "jvm_threads_daemon_threads{ instance=\"$instance\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "jvm_threads_peak_threads{ instance=\"$instance\"}",
     "legendFormat": "peak"
    },
    {
     "expr": "jvm_threads_started_threads_total{ instance=\"$instance\"}",
     "legendFormat": "process"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "jvm_threads_states_threads{state=\"blocked\", instance=\"$instance\"}",
     "legendFormat": "blocked"
    },
    {
     "expr": " jvm_threads_states_threads{state=\"new\", instance=\"$instance\"}",
     "legendFormat": "new"
    },
    {
     "expr": "jvm_threads_states_threads{state=\"runnable\"}",
     "legendFormat": "runnable"
    },
    {
     "expr": "jvm_threads_states_threads{state=\"terminated\"}",
     "legendFormat": "terminated"
    },
    {
     "expr": "jvm_threads_states_threads{state=\"timed-waiting\", instance=\"$instance\"}",
     "legendFormat": "timed-waiting"
    },
    {
     "expr": "jvm_threads_states_threads{state=\"waiting\", instance=\"$instance\"}",
     "legendFormat": "waiting"
    }
   ]
  },
  {
   "title": "Log Events",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "rate(logback_events_total{level=\"error\",instance=\"$instance\"}[5m])",
     "legendFormat": "error"
    },
    {
     "expr": "rate(logback_events_total{level=\"warn\", instance=\"$instance\"}[5m])",
     "legendFormat": "warn"
    },
    {
     "expr": "rate(logback_events_total{level=\"info\", instance=\"$instance\"}[5m])",
     "legendFormat": "info"
    },
    {
     "expr": "rate(logback_events_total{level=\"debug\", instance=\"$instance\"}[5m])",
     "legendFormat": "debug"
    },
    {
     "expr": "rate(logback_events_total{level=\"trace\", instance=\"$instance\"}[5m])",
     "legendFormat": "trace"
    }
   ]
  },
  {
   "title": "GC Pressure",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(jvm_gc_pause_seconds_sum{ instance=\"$instance\"}[5m])) / (sum(rate(process_cpu_time_ns_total{instance=\"$instance\"}[5m])) / 1e9)) * 100",
     "legendFormat": "CPU Time Spent on GC %"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 22 },
   "targets": [
    {
     "expr": "process_files_open_files{ instance=\"$instance\"}",
     "legendFormat": "open"
    },
    {
     "expr": "process_files_max_files{ instance=\"$instance\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Hikaricp active connections",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections_active{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hikaricp idle connections",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections_idle{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hikaricp connections timeout total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections_timeout_total{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}