apiVersion: 1
groups:
- name: ' PrometheusServer'
  folder: Ceph-Alert
  interval: 10s
  rules:
  - uid: denfq94rdg6wwf
    title: PrometheusJobMissing
    condition: C
    data:
    - refId: A
      relativeTimeRange:
        from: 600
        to: 0
      datasourceUid: aeoesbkofng1sf
      model:
        editorMode: code
        expr: absent(up{job="ceph"})
        instant: true
        intervalMs: 1000
        legendFormat: __auto
        maxDataPoints: 43200
        range: false
        refId: A
    - refId: C
      datasourceUid: __expr__
      model:
        conditions:
        - evaluator:
            params:
            - 0
            type: gt
          operator:
            type: and
          query:
            params:
            - C
          reducer:
            params: []
            type: last
          type: query
        datasource:
          type: __expr__
          uid: __expr__
        expression: A
        intervalMs: 1000
        maxDataPoints: 43200
        refId: C
        type: threshold
    noDataState: OK
    execErrState: Error
    for: 30s
    keepFiringFor: 1m
    annotations:
      description: The prometheus job that scrapes from Ceph is no longer defined,
        this will effectively mean you'll have no metrics or alerts for the cluster.  Please
        review the job definitions in the prometheus.yml file of the prometheus instance.
      summary: The scrape job for Ceph is missing from Prometheus
    labels:
      severity: critical
      storage: ceph
    isPaused: false
    notification_settings:
      receiver: grafana-default-email
