{
 "title": "Ceph Cluster",
 "description": "Overview of your Ceph cluster.",
 "tags": [ "ceph-mixin" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "CLUSTER STATE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ceph health status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ceph_health_status{}" }
   ]
  },
  {
   "title": "Monitors In Quorum",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_mon_quorum_status{}) or vector(0)"
    }
   ]
  },
  {
   "title": "Cluster Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ceph_cluster_total_bytes{}" }
   ]
  },
  {
   "title": "PG States",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(ceph_pg_total)", "legendFormat": "Total" },
    { "expr": "sum(ceph_pg_active)", "legendFormat": "Active" },
    {
     "expr": "sum(ceph_pg_total - ceph_pg_active)",
     "legendFormat": "Inactive"
    },
    { "expr": "sum(ceph_pg_undersized)", "legendFormat": "Undersized" },
    { "expr": "sum(ceph_pg_degraded)", "legendFormat": "Degraded" },
    { "expr": "sum(ceph_pg_inconsistent)", "legendFormat": "Inconsistent" },
    { "expr": "sum(ceph_pg_down)", "legendFormat": "Down" },
    { "expr": "sum(ceph_pg_incomplete{})", "legendFormat": "Incomplete" },
    {
     "expr": "    sum(ceph_pg_forced_backfill{})",
     "legendFormat": "Forced Backfill"
    },
    { "expr": "sum(ceph_pg_forced_recovery{})", "legendFormat": "Forced Recovery" },
    { "expr": "sum(ceph_pg_creating{})", "legendFormat": "Creating" },
    { "expr": "sum(ceph_pg_wait_backfill{})", "legendFormat": "Wait Backfill" },
    { "expr": "sum(ceph_pg_deep{})", "legendFormat": "Deep" },
    { "expr": "sum(ceph_pg_scrubbing{})", "legendFormat": "Scrubbing" },
    { "expr": "sum(ceph_pg_recovering{})", "legendFormat": "Recovering" },
    { "expr": "sum(ceph_pg_repair{})", "legendFormat": "Repair" },
    { "expr": "sum(ceph_pg_down{})", "legendFormat": "Down" },
    { "expr": "sum(ceph_pg_peered{})", "legendFormat": "Peered" },
    { "expr": "sum(ceph_pg_backfill{})", "legendFormat": "Backfill" },
    { "expr": "sum(ceph_pg_remapped{})", "legendFormat": "Remapped" },
    {
     "expr": "sum(ceph_pg_backfill_toofull{})",
     "legendFormat": "Backfill Toofull"
    }
   ]
  },
  {
   "title": "Available Capacity",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(ceph_cluster_total_bytes{}-ceph_cluster_total_used_bytes{})/ceph_cluster_total_bytes{}"
    }
   ]
  },
  {
   "title": "AVG CPU Busy",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(1 - (\r\n  avg by(instance) (\r\n    rate(node_cpu_seconds_total{mode='idle',instance=~\".*\"}[$__rate_interval]) or\r\n    rate(node_cpu{mode='idle',instance=~\".*\"}[$__rate_interval])\r\n  )\r\n))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_cluster_total_used_bytes{}"
    }
   ]
  },
  {
   "title": "AVG RAM Utilization",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg ((\r\n  (\r\n    node_memory_MemTotal{instance=~\".*\"} or\r\n    node_memory_MemTotal_bytes{instance=~\".*\"}\r\n  ) - ((\r\n    node_memory_MemFree{instance=~\".*\"} or\r\n    node_memory_MemFree_bytes{instance=~\".*\"}) +\r\n    (\r\n      node_memory_Cached{instance=~\".*\"} or\r\n      node_memory_Cached_bytes{instance=~\".*\"}\r\n    ) + (\r\n      node_memory_Buffers{instance=~\".*\"} or\r\n      node_memory_Buffers_bytes{instance=~\".*\"}\r\n    ) + (\r\n      node_memory_Slab{instance=~\".*\"} or\r\n      node_memory_Slab_bytes{instance=~\".*\"}\r\n    )\r\n  )\r\n) / (\r\n  node_memory_MemTotal{instance=~\".*\"} or\r\n   node_memory_MemTotal_bytes{instance=~\".*\"}\r\n))\r\n"
    }
   ]
  },
  {
   "title": "Number of Objects",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ceph_pool_objects{})" }
   ]
  },
  { "title": "OSD STATE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "OSDs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(ceph_osd_metadata)", "legendFormat": "All" },
    { "expr": "sum(ceph_osd_in)", "legendFormat": "In" },
    { "expr": "sum(ceph_osd_in == bool 0)", "legendFormat": "Out" },
    { "expr": "sum(ceph_osd_up)", "legendFormat": "Up" },
    { "expr": "sum(ceph_osd_up == bool 0)", "legendFormat": "Down" }
   ]
  },
  { "title": "CLUSTER STATS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ceph_cluster_total_bytes{}-ceph_cluster_total_used_bytes{}",
     "legendFormat": "Available"
    },
    {
     "expr": "ceph_cluster_total_used_bytes{}",
     "legendFormat": "Used"
    },
    { "expr": "ceph_cluster_total_bytes{}", "legendFormat": "Total Capacity" }
   ]
  },
  {
   "title": "Pool RAW Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(ceph_pool_avail_raw{}) *on (pool_id) group_left(name)(ceph_pool_metadata{})",
     "legendFormat": "{{name}} Avail"
    },
    {
     "expr": "(ceph_pool_stored_raw{}) *on (pool_id) group_left(name)(ceph_pool_metadata{})",
     "legendFormat": "{{name}} Stored"
    }
   ]
  },
  {
   "title": "Objects Per Pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(ceph_pool_objects{}) *on (pool_id) group_left(name)(ceph_pool_metadata{})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pool Used Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(ceph_pool_bytes_used{}) *on (pool_id) group_left(name)(ceph_pool_metadata{})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pool Objects Quota",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(ceph_pool_quota_objects{}) *on (pool_id) group_left(name)(ceph_pool_metadata{})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pool Quota Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(ceph_pool_quota_bytes{}) *on (pool_id) group_left(name)(ceph_pool_metadata{})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pool Overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "(\r\n  ceph_pool_compress_under_bytes{} /\r\n    ceph_pool_compress_bytes_used{ job=\"ceph-cluster\"} > 0\r\n) and on(pool_id) (\r\n  (\r\n    (ceph_pool_compress_under_bytes{ job=\"ceph-cluster\"} > 0) /\r\n      ceph_pool_stored_raw{ job=\"ceph-cluster\"}\r\n  ) * 100 > 0.5\r\n)",
     "legendFormat": "A"
    },
    {
     "expr": "(\r\n  (ceph_pool_compress_under_bytes{ job=\"ceph-cluster\"} > 0) /\r\n    ceph_pool_stored_raw{ job=\"ceph-cluster\"}\r\n) * 100\r\n",
     "legendFormat": "C"
    },
    {
     "expr": "ceph_pool_percent_used{ job=\"ceph-cluster\"} *\r\n  on(pool_id) group_left(name) ceph_pool_metadata{ job=\"ceph-cluster\"}",
     "legendFormat": "D"
    },
    {
     "expr": "ceph_pool_compress_under_bytes{ job=\"ceph-cluster\"} -\r\n  ceph_pool_compress_bytes_used{ job=\"ceph-cluster\"} > 0\r\n",
     "legendFormat": "E"
    },
    {
     "expr": "delta(ceph_pool_stored{ job=\"ceph-cluster\"}[5d])",
     "legendFormat": "F"
    },
    {
     "expr": "rate(ceph_pool_rd{ job=\"ceph-cluster\"}[$__rate_interval])\r\n  + rate(ceph_pool_wr{ job=\"ceph-cluster\"}[$__rate_interval])",
     "legendFormat": "G"
    },
    {
     "expr": "rate(ceph_pool_rd_bytes{ job=\"ceph-cluster\"}[$__rate_interval]) +\r\n  rate(ceph_pool_wr_bytes{ job=\"ceph-cluster\"}[$__rate_interval])",
     "legendFormat": "H"
    },
    {
     "expr": "ceph_pool_metadata{ job=\"ceph-cluster\"}",
     "legendFormat": "I"
    },
    {
     "expr": "ceph_pool_stored{ job=\"ceph-cluster\"} * on(pool_id) group_left ceph_pool_metadata{ job=\"ceph-cluster\"}",
     "legendFormat": "J"
    },
    {
     "expr": "ceph_pool_metadata{ compression_mode!=\"none\",job=\"ceph-cluster\"}",
     "legendFormat": "K"
    },
    {}
   ]
  },
  { "title": "Node Statistics (NodeExporter)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Node Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_Active_anon_bytes{}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(node_memory_Active_anon_bytes{})",
     "legendFormat": "Cluster Memory Usage"
    }
   ]
  },
  {
   "title": "Node In",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_disk_written_bytes_total{}[$interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Out",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_disk_read_bytes_total{}[$interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Free Space in root filesystem",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_filesystem_free_bytes{ mountpoint=\"/\", device != \"rootfs\"})*100 / (node_filesystem_size_bytes{ mountpoint=\"/\", device != \"rootfs\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "OBJECTS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "OSD Type Count",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(ceph_pool_objects)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "PGs State",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 6, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(ceph_pg_active{})", "legendFormat": "Active" },
    { "expr": "sum(ceph_pg_clean{})", "legendFormat": "Clean" },
    { "expr": "sum(ceph_pg_peering{})", "legendFormat": "Peering" },
    { "expr": "sum(ceph_pg_degraded{})", "legendFormat": "Degraded" },
    { "expr": "sum(ceph_pg_stale{})", "legendFormat": "Stale" },
    { "expr": "sum(ceph_unclean_pgs{})", "legendFormat": "Unclean" },
    { "expr": "sum(ceph_pg_undersized{})", "legendFormat": "Undersized" },
    { "expr": "sum(ceph_pg_incomplete{})", "legendFormat": "Incomplete" },
    { "expr": "sum(ceph_pg_forced_backfill{})", "legendFormat": "Forced Backfill" },
    { "expr": "sum(ceph_pg_forced_recovery{})", "legendFormat": "Forced Recovery" },
    { "expr": "sum(ceph_pg_creating{})", "legendFormat": "Creating" },
    { "expr": "sum(ceph_pg_wait_backfill{})", "legendFormat": "Wait Backfill" },
    { "expr": "sum(ceph_pg_deep{})", "legendFormat": "Deep" },
    { "expr": "sum(ceph_pg_scrubbing{})", "legendFormat": "Scrubbing" },
    { "expr": "sum(ceph_pg_recovering{})", "legendFormat": "Recovering" },
    { "expr": "sum(ceph_pg_repair{})", "legendFormat": "Repair" },
    { "expr": "sum(ceph_pg_down{})", "legendFormat": "Down" },
    { "expr": "sum(ceph_pg_peered{})", "legendFormat": "Peered" },
    { "expr": "sum(ceph_pg_backfill{})", "legendFormat": "Backfill" },
    { "expr": "sum(ceph_pg_remapped{})", "legendFormat": "Remapped" },
    {
     "expr": "sum(ceph_pg_backfill_toofull{})",
     "legendFormat": "Backfill Toofull"
    }
   ]
  },
  {
   "title": "Stuck PGs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(ceph_pg_degraded{})", "legendFormat": "Degraded" },
    { "expr": "sum(ceph_pg_stale{})", "legendFormat": "Stale" },
    { "expr": "sum(ceph_pg_undersized{})", "legendFormat": "Undersized" }
   ]
  },
  { "title": "LATENCY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "OSD Apply Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    { "expr": "ceph_osd_apply_latency_ms{}" }
   ]
  },
  {
   "title": "OSD Commit Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "targets": [
    { "expr": "ceph_osd_commit_latency_ms{}" }
   ]
  },
  {
   "title": "AVG OSD Apply + Commit Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(ceph_osd_apply_latency_ms{})",
     "legendFormat": "apply"
    },
    {
     "expr": "avg(ceph_osd_commit_latency_ms{})",
     "legendFormat": "commit"
    }
   ]
  },
  { "title": "Ceph Versions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Ceph OSD Versions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (ceph_version)(ceph_osd_metadata{})"
    }
   ]
  },
  {
   "title": "Ceph Mon Versions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (ceph_version)(ceph_mon_metadata{})"
    }
   ]
  },
  {
   "title": "Ceph MDS Versions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (ceph_version)(ceph_mds_metadata{})"
    }
   ]
  },
  {
   "title": "Ceph RGW Versions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (ceph_version)(ceph_rgw_metadata{})"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Logs",
     "type": "logs",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 161 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{job=\"Cluster Logs\"}"
      }
     ]
    }
   ]
  }
 ]
}