{
 "title": "CEPH RBD GUL",
 "time": { "from": "now-1m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Health Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ceph_health_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Hosts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (hostname) (ceph_osd_metadata))"
    }
   ]
  },
  {
   "title": "OSDs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(ceph_osd_metadata)", "legendFormat": "All" },
    { "expr": "sum(ceph_osd_in)", "legendFormat": "In" },
    { "expr": "sum(ceph_osd_in == bool 0)", "legendFormat": "Out" },
    { "expr": "sum(ceph_osd_up)", "legendFormat": "Up" },
    { "expr": "sum(ceph_osd_up == bool 0)", "legendFormat": "Down" }
   ]
  },
  {
   "title": "Memory usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance) (\r\n (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes)\r\n  / node_memory_MemTotal_bytes\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ceph_cluster_total_bytes{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceph_cluster_total_used_bytes{}"
    }
   ]
  },
  {
   "title": "AVG CPU Busy",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(1 - (\r\n  avg by(instance) (\r\n    rate(node_cpu_seconds_total{mode='idle',instance=~\".*\"}[$__rate_interval]) or\r\n    rate(node_cpu{mode='idle',instance=~\".*\"}[$__rate_interval])\r\n  )\r\n))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AVG RAM Utilization",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg ((\r\n  (\r\n    node_memory_MemTotal{instance=~\".*\"} or\r\n    node_memory_MemTotal_bytes{instance=~\".*\"}\r\n  ) - ((\r\n    node_memory_MemFree{instance=~\".*\"} or\r\n    node_memory_MemFree_bytes{instance=~\".*\"}) +\r\n    (\r\n      node_memory_Cached{instance=~\".*\"} or\r\n      node_memory_Cached_bytes{instance=~\".*\"}\r\n    ) + (\r\n      node_memory_Buffers{instance=~\".*\"} or\r\n      node_memory_Buffers_bytes{instance=~\".*\"}\r\n    ) + (\r\n      node_memory_Slab{instance=~\".*\"} or\r\n      node_memory_Slab_bytes{instance=~\".*\"}\r\n    )\r\n  )\r\n) / (\r\n  node_memory_MemTotal{instance=~\".*\"} or\r\n   node_memory_MemTotal_bytes{instance=~\".*\"}\r\n))\r\n"
    }
   ]
  },
  {
   "title": "PG States",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(ceph_pg_total)", "legendFormat": "Total" },
    { "expr": "sum(ceph_pg_active)", "legendFormat": "Active" },
    {
     "expr": "sum(ceph_pg_total - ceph_pg_active)",
     "legendFormat": "Inactive"
    },
    { "expr": "sum(ceph_pg_undersized)", "legendFormat": "Undersized" },
    { "expr": "sum(ceph_pg_degraded)", "legendFormat": "Degraded" },
    { "expr": "sum(ceph_pg_inconsistent)", "legendFormat": "Inconsistent" },
    { "expr": "sum(ceph_pg_down)", "legendFormat": "Down" },
    { "expr": "sum(ceph_pg_incomplete{})", "legendFormat": "Incomplete" },
    {
     "expr": "    sum(ceph_pg_forced_backfill{})",
     "legendFormat": "Forced Backfill"
    },
    { "expr": "sum(ceph_pg_forced_recovery{})", "legendFormat": "Forced Recovery" },
    { "expr": "sum(ceph_pg_creating{})", "legendFormat": "Creating" },
    { "expr": "sum(ceph_pg_wait_backfill{})", "legendFormat": "Wait Backfill" },
    { "expr": "sum(ceph_pg_deep{})", "legendFormat": "Deep" },
    { "expr": "sum(ceph_pg_scrubbing{})", "legendFormat": "Scrubbing" },
    { "expr": "sum(ceph_pg_recovering{})", "legendFormat": "Recovering" },
    { "expr": "sum(ceph_pg_repair{})", "legendFormat": "Repair" },
    { "expr": "sum(ceph_pg_down{})", "legendFormat": "Down" },
    { "expr": "sum(ceph_pg_peered{})", "legendFormat": "Peered" },
    { "expr": "sum(ceph_pg_backfill{})", "legendFormat": "Backfill" },
    { "expr": "sum(ceph_pg_remapped{})", "legendFormat": "Remapped" },
    {
     "expr": "sum(ceph_pg_backfill_toofull{})",
     "legendFormat": "Backfill Toofull"
    }
   ]
  },
  {
   "title": "Read Throughput",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_r_out_bytes{}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write Throughput",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_w_in_bytes{}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_w{}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_osd_op_r{}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RBD Read OPS",
   "type": "barchart",
   "description": "Top 10 Read OPS",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "topk(10, sum(rate(ceph_rbd_read_ops[1m])) by (pool, image))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RBD Write OPS",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "topk(10, sum(rate(ceph_rbd_write_ops[1m])) by (pool, image))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Host Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_network_receive_bytes_total{device!~\"lo\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "-1 * sum by (instance) (irate(node_network_transmit_bytes_total{device!~\"lo\"}[1m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network error rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "rate(node_network_receive_errs_total{ device!~\"^(lo).*\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "-1 * rate(node_network_transmit_errs_total{ device!~\"^(lo).*\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network drop rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 16 },
   "targets": [
    {
     "expr": "rate(node_network_receive_drop_total{ device!~\"^(lo).*\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "-1 * rate(node_network_transmit_drop_total{cluster=\"...\", device!~\"^(lo).*\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pool Overview",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "(\r\n  ceph_pool_compress_under_bytes{job=~\"ceph\"} /\r\n    ceph_pool_compress_bytes_used{job=~\"ceph\"} > 0\r\n) and on(pool_id) (\r\n  (\r\n    (ceph_pool_compress_under_bytes{job=~\"ceph\"} > 0) /\r\n      ceph_pool_stored_raw{job=~\"ceph\"}\r\n  ) * 100 > 0.5\r\n)",
     "legendFormat": "A"
    },
    {
     "expr": "ceph_pool_max_avail{job=~\"ceph\"} *\r\n  on(pool_id) group_left(name) ceph_pool_metadata{job=~\"ceph\"}\r\n",
     "legendFormat": "B"
    },
    {
     "expr": "(\r\n  (ceph_pool_compress_under_bytes{job=~\"ceph\"} > 0) /\r\n    ceph_pool_stored_raw{job=~\"ceph\"}\r\n) * 100\r\n",
     "legendFormat": "C"
    },
    {
     "expr": "ceph_pool_percent_used{job=~\"ceph\"} *\r\n  on(pool_id) group_left(name) ceph_pool_metadata{job=~\"ceph\"}",
     "legendFormat": "D"
    },
    {
     "expr": "ceph_pool_compress_under_bytes{job=~\"$job\"} -\r\n  ceph_pool_compress_bytes_used{job=~\"$job\"} > 0\r\n",
     "legendFormat": "E"
    },
    {
     "expr": "delta(ceph_pool_stored{job=~\"ceph\"}[5d])",
     "legendFormat": "F"
    },
    {
     "expr": "rate(ceph_pool_rd{job=~\"ceph\"}[$__rate_interval])\r\n  + rate(ceph_pool_wr{job=~\"ceph\"}[$__rate_interval])",
     "legendFormat": "G"
    },
    {
     "expr": "rate(ceph_pool_rd_bytes{job=~\"ceph\"}[$__rate_interval]) +\r\n  rate(ceph_pool_wr_bytes{job=~\"ceph\"}[$__rate_interval])",
     "legendFormat": "H"
    },
    {
     "expr": "ceph_pool_metadata{job=~\"ceph\"}",
     "legendFormat": "I"
    },
    {
     "expr": "ceph_pool_stored{job=~\"ceph\"} * on(pool_id) group_left ceph_pool_metadata{job=~\"ceph\"}",
     "legendFormat": "J"
    },
    {
     "expr": "ceph_pool_metadata{job=~\"ceph\", compression_mode!=\"none\"}",
     "legendFormat": "K"
    },
    {}
   ]
  }
 ]
}