{
 "title": "Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Server", "query": { "query": "label_values(job)" } },
   {
    "name": "Domain",
    "query": {
     "query": "label_values(probe_ssl_earliest_cert_expiry,instance)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {}
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {}
   },
   {
    "name": "search",
    "label": "Search Term",
    "query": "error|fatal,warn|error|fatal,fatal,error,warn,info,.+"
   }
  ]
 },
 "panels": [
  { "title": "$Domain Site Status Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime Percentage (Last 60 Days)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(probe_success{instance=\"$Domain\"}[60d])\r\n/\r\ncount_over_time(probe_success{instance=\"$Domain\"}[60d])\r\n* 100"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{instance=~\"$Domain\"}"
    }
   ]
  },
  {
   "title": "SSL Expiry",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=~\"$Domain\"} - time()"
    }
   ]
  },
  {
   "title": "StackBill Platform Layer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster memory usage",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",}) / sum (machine_memory_bytes{}) * 100"
      }
     ]
    },
    {
     "title": "Cluster CPU usage (1m avg)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\"}[1m])) / sum (machine_cpu_cores) * 100"
      }
     ]
    },
    {
     "title": "Cluster filesystem usage",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(container_fs_usage_bytes{device=\"/dev/mapper/ubuntu--vg-ubuntu--lv\",id=\"/\"}) / sum(container_fs_limit_bytes{device=\"/dev/mapper/ubuntu--vg-ubuntu--lv\",id=\"/\"}) * 100"
      }
     ]
    },
    {
     "title": "Logs Panel",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{namespace=~\"$namespace\", pod=~\"$pod\"} |~ \"(?i)$search\""
      }
     ]
    }
   ]
  },
  {
   "title": " CloudStack Orchestration Layer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hypervisor status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by(ip) (cloudstack_hosts_total{filter=\"online\"}))",
       "legendFormat": "Online"
      },
      {
       "expr": "(sum by(ip) (cloudstack_hosts_total{ filter=\"offline\"})) ",
       "legendFormat": "Offline"
      }
     ]
    },
    {
     "title": "cloudstack management service",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 7 },
     "targets": [
      {
       "expr": "label_replace(\r\n  node_systemd_unit_state{name=\"cloudstack-management.service\", state=~\"active|failed|inactive|deactivating|activating\",job!~\"MGT-01-BRK\"} == 1,\r\n  \"status\", \"$1\", \"state\", \"(.*)\"\r\n)",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "cloudstack usage service",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 7 },
     "targets": [
      {
       "expr": "label_replace(\r\n  node_systemd_unit_state{name=\"cloudstack-usage.service\", state=~\"active|failed|inactive|deactivating|activating\"} == 1,\r\n  \"status\", \"$1\", \"state\", \"(.*)\"\r\n)",
       "legendFormat": "{{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "$Server Uptime & Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - node_boot_time_seconds{job=\"$Server\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "RAM used ",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 * (node_memory_MemTotal_bytes{job=\"$Server\"} - node_memory_MemAvailable_bytes{job=\"$Server\"}) / node_memory_MemTotal_bytes{job=\"$Server\"}\r\n",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (job, mountpoint)(\r\n  (\r\n    node_filesystem_size_bytes{fstype=~\"xfs|ext4\",job=\"$Server\"}\r\n    - node_filesystem_free_bytes{fstype=~\"xfs|ext4\",job=\"$Server\"}\r\n  ) / node_filesystem_size_bytes{fstype=~\"xfs|ext4\",job=\"$Server\"} * 100\r\n)\r\n",
       "legendFormat": "{{job}} ({{mountpoint}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Ceph Storage Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "OBJ-BRK-Health Status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 197 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "ceph_health_status", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "RBD-BRK-Health Status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 197 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "ceph_health_status", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "RBD-GUL-Health Status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 197 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "ceph_health_status", "legendFormat": "__auto" }
     ]
    }
   ]
  }
 ]
}