{
 "title": "RabbitMQ - Queues",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "SB Total Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SbQueueEvent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_ready{queue=\"SbQueueEvent\", vhost=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SbWebsocketEvent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_ready{queue=\"SbWebsocketEvent\", vhost=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SbCronJobEvent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_ready{queue=\"SbCronJobEvent\", vhost=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WolfCmpResources",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_ready{queue=\"WolfCmpResources\", vhost=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WolfCoreServiceCommunicationEvent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_ready{queue=\"WolfCoreServiceCommunicationEvent\", vhost=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "ACS-Total-Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "WolfActionEvent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_ready{queue=\"WolfActionEvent\", vhost=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WolfAlertEvent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_ready{queue=\"WolfAlertEvent\", vhost=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WolfAsynchEvent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_ready{queue=\"WolfAsynchEvent\", vhost=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WolfResourceEvent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_ready{queue=\"WolfResourceEvent\", vhost=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WolfUsageEvent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_ready{queue=\"WolfUsageEvent\", vhost=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Email Total Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "WolfEmailTemplate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_ready{queue=\"WolfEmailTemplate\", vhost=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WolfEmailTemplateMailServer",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_ready{queue=\"WolfEmailTemplateMailServer\", vhost=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "StackWatch Total Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "sb_sw_alert_queue",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_ready{queue=\"sb_sw_alert_queue\", vhost=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "sb_sw_queue",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_ready{queue=\"sb_sw_queue\", vhost=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "SB Queue - Unack", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "SbQueueEvent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_unacked{queue=\"SbQueueEvent\", vhost=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SbWebsocketEvent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_unacked{queue=\"SbWebsocketEvent\", vhost=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SbCronJobEvent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_unacked{queue=\"SbCronJobEvent\", vhost=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WolfCmpResources",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_unacked{queue=\"WolfCmpResources\", vhost=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WolfCoreServiceCommunicationEvent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_unacked{queue=\"WolfCoreServiceCommunicationEvent\", vhost=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "ACS-Unack-Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "WolfActionEvent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_unacked{queue=\"WolfActionEvent\", vhost=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WolfAlertEvent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_unacked{queue=\"WolfAlertEvent\", vhost=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WolfAsynchEvent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_unacked{queue=\"WolfAsynchEvent\", vhost=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WolfResourceEvent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_unacked{queue=\"WolfResourceEvent\", vhost=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WolfUsageEvent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_unacked{queue=\"WolfUsageEvent\", vhost=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Emai Unack Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "WolfEmailTemplate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_unacked{queue=\"WolfEmailTemplate\", vhost=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WolfEmailTemplateMailServer",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_unacked{queue=\"WolfEmailTemplateMailServer\", vhost=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Stackwacth-Unack-Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "sb_sw_alert_queue",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_unacked{queue=\"sb_sw_alert_queue\", vhost=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "sb_sw_queue",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_unacked{queue=\"sb_sw_queue\", vhost=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}