{
 "title": "Server Monitoring",
 "tags": [ "linux" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "nodename",
    "label": "Nodename",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, nodename)"
    }
   },
   {
    "name": "node",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\", nodename=\"$nodename\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Quick CPU / Mem / Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pressure",
     "type": "bargauge",
     "description": "Resource pressure via PSI",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "irate(node_pressure_cpu_waiting_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "CPU"
      },
      {
       "expr": "irate(node_pressure_memory_waiting_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Mem"
      },
      {
       "expr": "irate(node_pressure_io_waiting_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "I/O"
      },
      {
       "expr": "irate(node_pressure_irq_stalled_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Irq"
      }
     ]
    },
    {
     "title": "CPU Busy",
     "type": "gauge",
     "description": "Overall CPU busy percentage (averaged across all cores)",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$node\"}[$__rate_interval])))"
      }
     ]
    },
    {
     "title": "Sys Load",
     "type": "gauge",
     "description": "System load  over all CPU cores together",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "scalar(node_load1{instance=\"$node\",job=\"$job\"}) * 100 / count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))"
      }
     ]
    },
    {
     "title": "RAM Used",
     "type": "gauge",
     "description": "Real RAM usage excluding cache and reclaimable memory",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "clamp_min((1 - (node_memory_MemAvailable_bytes{instance=\"$node\", job=\"$job\"} / node_memory_MemTotal_bytes{instance=\"$node\", job=\"$job\"})) * 100, 0)"
      }
     ]
    },
    {
     "title": "SWAP Used",
     "type": "gauge",
     "description": "Percentage of swap space currently used by the system",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"}) / (node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"})) * 100"
      }
     ]
    },
    {
     "title": "Root FS Used",
     "type": "gauge",
     "description": "Used Root FS",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\n  (node_filesystem_size_bytes{instance=\"$node\", job=\"$job\", mountpoint=\"/\", fstype!=\"rootfs\"}\n   - node_filesystem_avail_bytes{instance=\"$node\", job=\"$job\", mountpoint=\"/\", fstype!=\"rootfs\"})\n  / node_filesystem_size_bytes{instance=\"$node\", job=\"$job\", mountpoint=\"/\", fstype!=\"rootfs\"}\n) * 100\n"
      }
     ]
    },
    {
     "title": "CPU Cores",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RAM Total",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 20, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}"
      }
     ]
    },
    {
     "title": "SWAP Total",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 22, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"}"
      }
     ]
    },
    {
     "title": "RootFS Total",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 18, "y": 317 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 20, "y": 317 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_time_seconds{instance=\"$node\",job=\"$job\"} - node_boot_time_seconds{instance=\"$node\",job=\"$job\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU / Memory / Net / Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "description": "CPU time usage split by state, normalized across all CPU cores",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(irate(node_cpu_seconds_total{mode=\"system\",instance=\"$node\",job=\"$job\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
       "legendFormat": "System - Processes executing in kernel mode"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{mode=\"user\",instance=\"$node\",job=\"$job\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
       "legendFormat": "User - Normal processes executing in user mode"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{mode=\"nice\",instance=\"$node\",job=\"$job\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
       "legendFormat": "Nice - Niced processes executing in user mode"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{mode=\"iowait\",instance=\"$node\",job=\"$job\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
       "legendFormat": "Iowait - Waiting for I/O to complete"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{mode=\"irq\",instance=\"$node\",job=\"$job\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
       "legendFormat": "Irq - Servicing interrupts"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{mode=\"softirq\",instance=\"$node\",job=\"$job\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
       "legendFormat": "Softirq - Servicing softirqs"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{mode=\"steal\",instance=\"$node\",job=\"$job\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
       "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{mode=\"idle\",instance=\"$node\",job=\"$job\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
       "legendFormat": "Idle - Waiting for something to happen"
      },
      {
       "expr": "sum by(instance) (irate(node_cpu_guest_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval]))) > 0",
       "legendFormat": "Guest CPU usage"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "description": "Breakdown of physical memory and swap usage. Hardware-detected memory errors are also displayed",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"} - node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"} - node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"} - node_memory_Slab_bytes{instance=\"$node\",job=\"$job\"} - node_memory_PageTables_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapCached_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Apps - Memory used by user-space applications"
      },
      {
       "expr": "node_memory_PageTables_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "PageTables - Memory used to map between virtual and physical memory addresses"
      },
      {
       "expr": "node_memory_SwapCached_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "SwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified"
      },
      {
       "expr": "node_memory_Slab_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Slab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Cache - Parked file data (file content) cache"
      },
      {
       "expr": "node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Buffers - Block device (e.g. harddisk) cache"
      },
      {
       "expr": "node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Unused - Free memory unassigned"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"})",
       "legendFormat": "Swap - Swap space used"
      },
      {
       "expr": "node_memory_HardwareCorrupted_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Hardware Corrupted - Amount of RAM that the kernel identified as corrupted / not working"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "timeseries",
     "description": "Incoming and outgoing network traffic per interface",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])*8",
       "legendFormat": "{{device}} - Rx in"
      },
      {
       "expr": "rate(node_network_transmit_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])*8",
       "legendFormat": "{{device}} - Tx out"
      }
     ]
    },
    {
     "title": "Network Saturation",
     "type": "timeseries",
     "description": "Network interface utilization as a percentage of its maximum capacity",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])\n / ignoring(speed) node_network_speed_bytes{instance=\"$node\",job=\"$job\", speed!=\"-1\"}",
       "legendFormat": "{{device}} - Rx in"
      },
      {
       "expr": "(rate(node_network_transmit_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])\n / ignoring(speed) node_network_speed_bytes{instance=\"$node\",job=\"$job\", speed!=\"-1\"})",
       "legendFormat": "{{device}} - Tx out"
      }
     ]
    },
    {
     "title": "Disk IOps",
     "type": "timeseries",
     "description": "Disk I/O operations per second for each device",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{instance=\"$node\",job=\"$job\",device=~\"[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Read"
      },
      {
       "expr": "irate(node_disk_writes_completed_total{instance=\"$node\",job=\"$job\",device=~\"[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Write"
      }
     ]
    },
    {
     "title": "Disk Throughput",
     "type": "timeseries",
     "description": "Disk I/O throughput per device",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{instance=\"$node\",job=\"$job\",device=~\"[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Read"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{instance=\"$node\",job=\"$job\",device=~\"[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Write"
      }
     ]
    },
    {
     "title": "Filesystem Space Available",
     "type": "timeseries",
     "description": "Amount of available disk space per mounted filesystem, excluding rootfs. Based on block availability to non-root users",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Filesystem Used",
     "type": "timeseries",
     "description": "Disk usage (used = total - available) per mountpoint",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",device!~'rootfs'} - node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Disk I/O Utilization",
     "type": "timeseries",
     "description": "Percentage of time the disk was actively processing I/O operations",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "irate(node_disk_io_time_seconds_total{instance=\"$node\",job=\"$job\",device=~\"[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+\"} [$__rate_interval])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Pressure Stall Information",
     "type": "timeseries",
     "description": "How often tasks experience CPU, memory, or I/O delays. “Some” indicates partial slowdown; “Full” indicates all tasks are stalled. Based on Linux PSI metrics:\nhttps://docs.kernel.org/accounting/psi.html",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(node_pressure_cpu_waiting_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "CPU - Some"
      },
      {
       "expr": "rate(node_pressure_memory_waiting_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Memory - Some"
      },
      {
       "expr": "rate(node_pressure_memory_stalled_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Memory - Full"
      },
      {
       "expr": "rate(node_pressure_io_waiting_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "I/O - Some"
      },
      {
       "expr": "rate(node_pressure_io_stalled_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "I/O - Full"
      },
      {
       "expr": "rate(node_pressure_irq_stalled_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "IRQ - Full"
      }
     ]
    }
   ]
  },
  { "title": "Memory Meminfo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Memory Committed",
   "type": "timeseries",
   "description": "Displays committed memory usage versus the system's commit limit. Exceeding the limit is allowed under Linux overcommit policies but may increase OOM risks under high load",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_Committed_AS_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Committed_AS – Memory promised to processes (not necessarily used)"
    },
    {
     "expr": "node_memory_CommitLimit_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "CommitLimit - Max allowable committed memory"
    }
   ]
  },
  {
   "title": "Memory Writeback and Dirty",
   "type": "timeseries",
   "description": "Memory currently dirty (modified but not yet written to disk), being actively written back, or held by writeback buffers. High dirty or writeback memory may indicate disk I/O pressure or delayed flushing",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_Writeback_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Writeback – Memory currently being flushed to disk"
    },
    {
     "expr": "node_memory_WritebackTmp_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "WritebackTmp – FUSE temporary writeback buffers"
    },
    {
     "expr": "node_memory_Dirty_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Dirty – Memory marked dirty (pending write to disk)"
    },
    {
     "expr": "node_memory_NFS_Unstable_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "NFS Unstable – Pages sent to NFS server, awaiting storage commit"
    }
   ]
  },
  {
   "title": "Memory Slab",
   "type": "timeseries",
   "description": "Kernel slab memory usage, separated into reclaimable and non-reclaimable categories. Reclaimable memory can be freed under memory pressure (e.g., caches), while unreclaimable memory is locked by the kernel for core functions",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_SUnreclaim_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "SUnreclaim – Non-reclaimable slab memory (kernel objects)"
    },
    {
     "expr": "node_memory_SReclaimable_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "SReclaimable – Potentially reclaimable slab memory (e.g., inode cache)"
    }
   ]
  },
  {
   "title": "Memory Shared and Mapped",
   "type": "timeseries",
   "description": "Memory used for mapped files (such as libraries) and shared memory (shmem and tmpfs), including variants backed by huge pages",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_Mapped_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Mapped – Memory mapped from files (e.g., libraries, mmap)"
    },
    {
     "expr": "node_memory_Shmem_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Shmem – Shared memory used by processes and tmpfs"
    },
    {
     "expr": "node_memory_ShmemHugePages_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "ShmemHugePages – Shared memory (shmem/tmpfs) allocated with HugePages"
    },
    {
     "expr": "node_memory_ShmemPmdMapped_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "PMD Mapped – Shmem/tmpfs backed by Transparent HugePages (PMD)"
    }
   ]
  },
  {
   "title": "Memory LRU Active / Inactive (%)",
   "type": "timeseries",
   "description": "Proportion of memory pages in the kernel's active and inactive LRU lists relative to total RAM. Active pages have been recently used, while inactive pages are less recently accessed but still resident in memory",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(node_memory_Inactive_bytes{instance=\"$node\",job=\"$job\"}) \n/ \n(node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"})",
     "legendFormat": "Inactive – Less recently used memory, more likely to be reclaimed"
    },
    {
     "expr": "(node_memory_Active_bytes{instance=\"$node\",job=\"$job\"}) \n/ \n(node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"})\n",
     "legendFormat": "Active – Recently used memory, retained unless under pressure"
    }
   ]
  },
  {
   "title": "Memory LRU Active / Inactive Detail",
   "type": "timeseries",
   "description": "Breakdown of memory pages in the kernel's active and inactive LRU lists, separated by anonymous (heap, tmpfs) and file-backed (caches, mmap) pages.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_Inactive_file_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Inactive_file - File-backed memory on inactive LRU list"
    },
    {
     "expr": "node_memory_Inactive_anon_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Inactive_anon – Anonymous memory on inactive LRU (incl. tmpfs & swap cache)"
    },
    {
     "expr": "node_memory_Active_file_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Active_file - File-backed memory on active LRU list"
    },
    {
     "expr": "node_memory_Active_anon_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Active_anon – Anonymous memory on active LRU (incl. tmpfs & swap cache)"
    }
   ]
  },
  {
   "title": "Memory Kernel / CPU / IO",
   "type": "timeseries",
   "description": "Tracks kernel memory used for CPU-local structures, per-thread stacks, and bounce buffers used for I/O on DMA-limited devices. These areas are typically small but critical for low-level operations",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_KernelStack_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "KernelStack – Kernel stack memory (per-thread, non-reclaimable)"
    },
    {
     "expr": "node_memory_Percpu_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "PerCPU – Dynamically allocated per-CPU memory (used by kernel modules)"
    },
    {
     "expr": "node_memory_Bounce_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Bounce Memory – I/O buffer for DMA-limited devices"
    }
   ]
  },
  {
   "title": "Memory Vmalloc",
   "type": "timeseries",
   "description": "Usage of the kernel's vmalloc area, which provides virtual memory allocations for kernel modules and drivers. Includes total, used, and largest free block sizes",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_VmallocChunk_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Vmalloc Free Chunk – Largest available block in vmalloc area"
    },
    {
     "expr": "node_memory_VmallocTotal_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Vmalloc Total – Total size of the vmalloc memory area"
    },
    {
     "expr": "node_memory_VmallocUsed_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Vmalloc Used – Portion of vmalloc area currently in use"
    }
   ]
  },
  {
   "title": "Memory Anonymous",
   "type": "timeseries",
   "description": "Memory used by anonymous pages (not backed by files), including standard and huge page allocations. Includes heap, stack, and memory-mapped anonymous regions",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_AnonHugePages_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "AnonHugePages – Anonymous memory using HugePages"
    },
    {
     "expr": "node_memory_AnonPages_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "AnonPages – Anonymous memory (non-file-backed)"
    }
   ]
  },
  {
   "title": "Memory Unevictable and MLocked",
   "type": "timeseries",
   "description": "Memory that is locked in RAM and cannot be swapped out. Includes both kernel-unevictable memory and user-level memory locked with mlock()",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_Unevictable_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Unevictable – Kernel-pinned memory (not swappable)"
    },
    {
     "expr": "node_memory_Mlocked_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Mlocked – Application-locked memory via mlock()"
    }
   ]
  },
  {
   "title": "Memory DirectMap",
   "type": "timeseries",
   "description": "How much memory is directly mapped in the kernel using different page sizes (4K, 2M, 1G). Helps monitor large page utilization in the direct map region",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_DirectMap1G_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "DirectMap 1G – Memory mapped with 1GB pages"
    },
    {
     "expr": "node_memory_DirectMap2M_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "DirectMap 2M – Memory mapped with 2MB pages"
    },
    {
     "expr": "node_memory_DirectMap4k_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "DirectMap 4K – Memory mapped with 4KB pages"
    }
   ]
  },
  {
   "title": "Memory HugePages",
   "type": "timeseries",
   "description": "Displays HugePages memory usage in bytes, including allocated, free, reserved, and surplus memory. All values are calculated based on the number of huge pages multiplied by their configured size",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_HugePages_Free{instance=\"$node\",job=\"$job\"} * node_memory_Hugepagesize_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "HugePages Used – Currently allocated"
    },
    {
     "expr": "node_memory_HugePages_Rsvd{instance=\"$node\",job=\"$job\"} * node_memory_Hugepagesize_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "HugePages Reserved – Promised but unused"
    },
    {
     "expr": "node_memory_HugePages_Surp{instance=\"$node\",job=\"$job\"} * node_memory_Hugepagesize_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "HugePages Surplus – Dynamic pool extension"
    },
    {
     "expr": "node_memory_HugePages_Total{instance=\"$node\",job=\"$job\"} * node_memory_Hugepagesize_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "HugePages Total – Reserved memory"
    }
   ]
  },
  {
   "title": "Memory Vmstat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Pages In / Out",
     "type": "timeseries",
     "description": "Rate of memory pages being read from or written to disk (page-in and page-out operations). High page-out may indicate memory pressure or swapping activity",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "irate(node_vmstat_pgpgin{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Pagesin - Page in ops"
      },
      {
       "expr": "irate(node_vmstat_pgpgout{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Pagesout - Page out ops"
      }
     ]
    },
    {
     "title": "Memory Pages Swap In / Out",
     "type": "timeseries",
     "description": "Rate at which memory pages are being swapped in from or out to disk. High swap-out activity may indicate memory pressure",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "irate(node_vmstat_pswpin{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Pswpin - Pages swapped in"
      },
      {
       "expr": "irate(node_vmstat_pswpout{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Pswpout - Pages swapped out"
      }
     ]
    },
    {
     "title": "Memory Page Faults",
     "type": "timeseries",
     "description": "Rate of memory page faults, split into total, major (disk-backed), and derived minor (non-disk) faults. High major fault rates may indicate memory pressure or insufficient RAM",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 134 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "irate(node_vmstat_pgfault{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Pgfault - Page major and minor fault ops"
      },
      {
       "expr": "irate(node_vmstat_pgmajfault{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Pgmajfault - Major page fault ops"
      },
      {
       "expr": "irate(node_vmstat_pgfault{instance=\"$node\",job=\"$job\"}[$__rate_interval])  - irate(node_vmstat_pgmajfault{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Pgminfault - Minor page fault ops"
      }
     ]
    },
    {
     "title": "OOM Killer",
     "type": "timeseries",
     "description": "Rate of Out-of-Memory (OOM) kill events. A non-zero value indicates the kernel has terminated one or more processes due to memory exhaustion",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 134 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "irate(node_vmstat_oom_kill{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "OOM Kills"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Read/Write IOps",
     "type": "timeseries",
     "description": "Number of I/O operations completed per second for the device (after merges), including both reads and writes",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 145 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Read"
      },
      {
       "expr": "irate(node_disk_writes_completed_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Write"
      }
     ]
    },
    {
     "title": "Disk Read/Write Data",
     "type": "timeseries",
     "description": "Number of bytes read from or written to the device per second",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 145 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Read"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Write"
      }
     ]
    },
    {
     "title": "Disk Average Wait Time",
     "type": "timeseries",
     "description": "Average time for requests issued to the device to be served. This includes the time spent by the requests in queue and the time spent servicing them.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 155 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(node_disk_read_time_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval]) / irate(node_disk_reads_completed_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Read"
      },
      {
       "expr": "irate(node_disk_write_time_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval]) / irate(node_disk_writes_completed_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Write"
      }
     ]
    },
    {
     "title": "Average Queue Size",
     "type": "timeseries",
     "description": "Average queue length of the requests that were issued to the device",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 155 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(node_disk_io_time_weighted_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk R/W Merged",
     "type": "timeseries",
     "description": "Number of read and write requests merged per second that were queued to the device",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 165 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "irate(node_disk_reads_merged_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Read"
      },
      {
       "expr": "irate(node_disk_writes_merged_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Write"
      }
     ]
    },
    {
     "title": "Time Spent Doing I/Os",
     "type": "timeseries",
     "description": "Percentage of time the disk spent actively processing I/O operations, including general I/O, discards (TRIM), and write cache flushes",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 165 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "irate(node_disk_io_time_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - General IO"
      },
      {
       "expr": "irate(node_disk_discard_time_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Discard/TRIM"
      },
      {
       "expr": "irate(node_disk_flush_requests_time_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Flush (write cache)"
      }
     ]
    },
    {
     "title": "Disk Ops Discards / Flush",
     "type": "timeseries",
     "description": "Per-second rate of discard (TRIM) and flush (write cache) operations. Useful for monitoring low-level disk activity on SSDs and advanced storage",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 175 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "irate(node_disk_discards_completed_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Discards completed"
      },
      {
       "expr": "irate(node_disk_discards_merged_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Discards merged"
      },
      {
       "expr": "irate(node_disk_flush_requests_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Flush"
      }
     ]
    },
    {
     "title": "Disk Sectors Discarded Successfully",
     "type": "timeseries",
     "description": "Shows how many disk sectors are discarded (TRIMed) per second. Useful for monitoring SSD behavior and storage efficiency",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 175 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(node_disk_discarded_sectors_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Instantaneous Queue Size",
     "type": "timeseries",
     "description": "Number of in-progress I/O requests at the time of sampling (active requests in the disk queue)",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 185 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_disk_io_now{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "{{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffic by Packets",
     "type": "timeseries",
     "description": "Number of network packets received and transmitted per second, by interface.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4479 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_packets_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Rx in"
      },
      {
       "expr": "rate(node_network_transmit_packets_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Tx out"
      }
     ]
    },
    {
     "title": "Network Traffic Errors",
     "type": "timeseries",
     "description": "Rate of packet-level errors for each network interface. Receive errors may indicate physical or driver issues; transmit errors may reflect collisions or hardware faults",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4479 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_errs_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Rx in"
      },
      {
       "expr": "rate(node_network_transmit_errs_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Tx out"
      }
     ]
    },
    {
     "title": "Network Traffic Drop",
     "type": "timeseries",
     "description": "Rate of dropped packets per network interface. Receive drops can indicate buffer overflow or driver issues; transmit drops may result from outbound congestion or queuing limits",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4489 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_drop_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Rx in"
      },
      {
       "expr": "rate(node_network_transmit_drop_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Tx out"
      }
     ]
    },
    {
     "title": "Network Traffic Compressed",
     "type": "timeseries",
     "description": "Rate of compressed network packets received and transmitted per interface. These are common in low-bandwidth or special interfaces like PPP or SLIP",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4489 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_compressed_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Rx in"
      },
      {
       "expr": "rate(node_network_transmit_compressed_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Tx out"
      }
     ]
    },
    {
     "title": "Network Traffic Multicast",
     "type": "timeseries",
     "description": "Rate of incoming multicast packets received per network interface. Multicast is used by protocols such as mDNS, SSDP, and some streaming or cluster services",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4499 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_multicast_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Rx in"
      }
     ]
    },
    {
     "title": "Network Traffic NoHandler",
     "type": "timeseries",
     "description": "Rate of received packets that could not be processed due to missing protocol or handler in the kernel. May indicate unsupported traffic or misconfiguration",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4499 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_nohandler_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Rx in"
      }
     ]
    },
    {
     "title": "Network Traffic Frame",
     "type": "timeseries",
     "description": "Rate of frame errors on received packets, typically caused by physical layer issues such as bad cables, duplex mismatches, or hardware problems",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4509 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_frame_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Rx in"
      }
     ]
    },
    {
     "title": "Network Traffic Fifo",
     "type": "timeseries",
     "description": "Tracks FIFO buffer overrun errors on network interfaces. These occur when incoming or outgoing packets are dropped due to queue or buffer overflows, often indicating congestion or hardware limits",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4509 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_fifo_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Rx in"
      },
      {
       "expr": "rate(node_network_transmit_fifo_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Tx out"
      }
     ]
    },
    {
     "title": "Network Traffic Collision",
     "type": "timeseries",
     "description": "Rate of packet collisions detected during transmission. Mostly relevant on half-duplex or legacy Ethernet networks",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4519 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(node_network_transmit_colls_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Tx out"
      }
     ]
    },
    {
     "title": "Network Traffic Carrier Errors",
     "type": "timeseries",
     "description": "Rate of carrier errors during transmission. These typically indicate physical layer issues like faulty cabling or duplex mismatches",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4519 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(node_network_transmit_carrier_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Tx out"
      }
     ]
    },
    {
     "title": "ARP Entries",
     "type": "timeseries",
     "description": "Number of ARP entries per interface. Useful for detecting excessive ARP traffic or table growth due to scanning or misconfiguration",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4529 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_arp_entries{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "{{ device }} ARP Table"
      }
     ]
    },
    {
     "title": "NF Conntrack",
     "type": "timeseries",
     "description": "Current and maximum connection tracking entries used by Netfilter (nf_conntrack). High usage approaching the limit may cause packet drops or connection issues",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4529 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_nf_conntrack_entries{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "NF conntrack entries"
      },
      {
       "expr": "node_nf_conntrack_entries_limit{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "NF conntrack limit"
      }
     ]
    },
    {
     "title": "Network Operational Status",
     "type": "timeseries",
     "description": "Operational and physical link status of each network interface. Values are Yes for 'up' or link present, and No for 'down' or no carrier.\"",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4539 },
     "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
     "targets": [
      {
       "expr": "node_network_carrier{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "{{device}} - Physical link"
      }
     ]
    },
    {
     "title": "Speed",
     "type": "bargauge",
     "description": "Maximum speed of each network interface as reported by the operating system. This is a static hardware capability, not current throughput",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 4539 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_network_speed_bytes{instance=\"$node\",job=\"$job\"} * 8",
       "legendFormat": "{{ device }}"
      }
     ]
    },
    {
     "title": "MTU",
     "type": "bargauge",
     "description": "MTU (Maximum Transmission Unit) in bytes for each network interface. Affects packet size and transmission efficiency",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 4539 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_network_mtu_bytes{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "{{ device }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Netstat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "collapsed": true,
   "panels": [
    {
     "title": "Netstat IP In / Out Octets",
     "type": "timeseries",
     "description": "Rate of octets sent and received at the IP layer, as reported by /proc/net/netstat",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4811 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "irate(node_netstat_IpExt_InOctets{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "IP Rx in"
      },
      {
       "expr": "irate(node_netstat_IpExt_OutOctets{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "IP Tx out"
      }
     ]
    },
    {
     "title": "TCP In / Out",
     "type": "timeseries",
     "description": "Rate of TCP segments sent and received per second, including data and control segments",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4811 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(node_netstat_Tcp_InSegs{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "TCP Rx in"
      },
      {
       "expr": "irate(node_netstat_Tcp_OutSegs{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "TCP Tx out"
      }
     ]
    },
    {
     "title": "UDP In / Out",
     "type": "timeseries",
     "description": "Rate of UDP datagrams sent and received per second, based on /proc/net/netstat",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4821 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(node_netstat_Udp_InDatagrams{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "UDP Rx in"
      },
      {
       "expr": "irate(node_netstat_Udp_OutDatagrams{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "UDP Tx out"
      }
     ]
    },
    {
     "title": "ICMP In / Out",
     "type": "timeseries",
     "description": "Number of ICMP messages sent and received per second, including error and control messages",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4821 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(node_netstat_Icmp_InMsgs{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "ICMP Rx in"
      },
      {
       "expr": "irate(node_netstat_Icmp_OutMsgs{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "ICMP Tx out"
      }
     ]
    },
    {
     "title": "TCP Errors",
     "type": "timeseries",
     "description": "Tracks various TCP error and congestion-related events, including retransmissions, timeouts, dropped connections, and buffer issues",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4831 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_ListenOverflows{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Listen Overflows"
      },
      {
       "expr": "irate(node_netstat_TcpExt_ListenDrops{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Listen Drops"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPSynRetrans{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "SYN Retransmits"
      },
      {
       "expr": "irate(node_netstat_Tcp_RetransSegs{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Segment Retransmits"
      },
      {
       "expr": "irate(node_netstat_Tcp_InErrs{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Receive Errors"
      },
      {
       "expr": "irate(node_netstat_Tcp_OutRsts{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "RST Sent"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPRcvQDrop{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Receive Queue Drops"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPOFOQueue{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Out-of-order Queued"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPTimeouts{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "TCP Timeouts"
      }
     ]
    },
    {
     "title": "UDP Errors",
     "type": "timeseries",
     "description": "Rate of UDP and UDPLite datagram delivery errors, including missing listeners, buffer overflows, and protocol-specific issues",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4831 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(node_netstat_Udp_InErrors{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "UDP Rx in Errors"
      },
      {
       "expr": "irate(node_netstat_Udp_NoPorts{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "UDP No Listener"
      },
      {
       "expr": "irate(node_netstat_UdpLite_InErrors{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "UDPLite Rx in Errors"
      },
      {
       "expr": "irate(node_netstat_Udp_RcvbufErrors{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "UDP Rx in Buffer Errors"
      },
      {
       "expr": "irate(node_netstat_Udp_SndbufErrors{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "UDP Tx out Buffer Errors"
      }
     ]
    },
    {
     "title": "ICMP Errors",
     "type": "timeseries",
     "description": "Rate of incoming ICMP messages that contained protocol-specific errors, such as bad checksums or invalid lengths",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4841 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(node_netstat_Icmp_InErrors{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "ICMP Rx In"
      }
     ]
    },
    {
     "title": "TCP SynCookie",
     "type": "timeseries",
     "description": "Rate of TCP SYN cookies sent, validated, and failed. These are used to protect against SYN flood attacks and manage TCP handshake resources under load",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4841 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_SyncookiesFailed{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "SYN Cookies Failed"
      },
      {
       "expr": "irate(node_netstat_TcpExt_SyncookiesRecv{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "SYN Cookies Validated"
      },
      {
       "expr": "irate(node_netstat_TcpExt_SyncookiesSent{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "SYN Cookies Sent"
      }
     ]
    },
    {
     "title": "TCP Connections",
     "type": "timeseries",
     "description": "Number of currently established TCP connections and the system's max supported limit. On Linux, MaxConn may return -1 to indicate a dynamic/unlimited configuration",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4851 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Current Connections"
      },
      {
       "expr": "node_netstat_Tcp_MaxConn{instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Max Connections"
      }
     ]
    },
    {
     "title": "UDP Queue",
     "type": "timeseries",
     "description": "Number of UDP packets currently queued in the receive (RX) and transmit (TX) buffers. A growing queue may indicate a bottleneck",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4851 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_udp_queues{instance=\"$node\",job=\"$job\",ip=\"v4\",queue=\"rx\"}",
       "legendFormat": "UDP Rx in Queue"
      },
      {
       "expr": "node_udp_queues{instance=\"$node\",job=\"$job\",ip=\"v4\",queue=\"tx\"}",
       "legendFormat": "UDP Tx out Queue"
      }
     ]
    },
    {
     "title": "TCP Direct Transition",
     "type": "timeseries",
     "description": "Rate of TCP connection initiations per second. 'Active' opens are initiated by this host. 'Passive' opens are accepted from incoming connections",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4861 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "irate(node_netstat_Tcp_ActiveOpens{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Active Opens"
      },
      {
       "expr": "irate(node_netstat_Tcp_PassiveOpens{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Passive Opens"
      }
     ]
    },
    {
     "title": "TCP Stat",
     "type": "timeseries",
     "description": "Number of TCP sockets in key connection states. Requires the --collector.tcpstat flag on node_exporter",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4861 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_tcp_connection_states{state=\"established\",instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Established"
      },
      {
       "expr": "node_tcp_connection_states{state=\"fin_wait2\",instance=\"$node\",job=\"$job\"}",
       "legendFormat": "FIN_WAIT2"
      },
      {
       "expr": "node_tcp_connection_states{state=\"listen\",instance=\"$node\",job=\"$job\"}",
       "legendFormat": "Listen"
      },
      {
       "expr": "node_tcp_connection_states{state=\"time_wait\",instance=\"$node\",job=\"$job\"}",
       "legendFormat": "TIME_WAIT"
      },
      {
       "expr": "node_tcp_connection_states{state=\"close_wait\", instance=\"$node\", job=\"$job\"}",
       "legendFormat": "CLOSE_WAIT"
      }
     ]
    }
   ]
  }
 ]
}